import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import FixedNavBar from '@/components/sharedUI/FixedNavBar'
import Header from '@/components/sharedUI/Header'
import Footer from '@/components/sharedUI/Footer'
import { StoreProvider } from '@/store/StoreProvider'
import Template from './template'
import { NextAuthProvider } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NextJS E-commerce example',
  description: 'Generated by create next app',
}

export default function RootLayout({ children } : { children: React.ReactNode }) {
  return (
    <>
      <html lang="fr">
        <body className={inter.className} suppressHydrationWarning >  
          <Template>
            <NextAuthProvider>
              <StoreProvider>
                <Header/>
                <FixedNavBar/>
                {children}
                <Footer/>
              </StoreProvider>
            </NextAuthProvider>
          </Template>
        </body>
      </html>
    </>
  )
}
